name: Build LaTeX document and Release PDF
  # Controls when the action will run.
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
  # https://mrturkmen.com/posts/build-release-latex/
on:
  workflow_dispatch:
    inputs: 
      file2compile:
         description: "Name of .tex file to compile, without the .tex part"
         required: true
         default: "main"
jobs:
  # followed: https://dev.to/dessygil/
  #   how-to-automatically-update-resume-on-your-personal-site-from-overleaf-1fld
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install TeX Live  packages
        run: sudo apt install -y texlive-base latexmk
      - name: Compile the LaTeX document
        run: latexmk -interaction=nonstopmode -file-line-error "${{ github.event.inputs.file2compile }}.tex"
#      - name: Compile LaTeX document
#        uses: xu-cheng/latex-action@3.2.0
#        with:
#          root_file: "${{ github.event.inputs.file2compile }}.tex"
#          continue_on_error: true 
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with: 
          name: PDF
          path: "${{ github.event.inputs.file2compile }}.pdf"
      - name: Publish PDF to repo
        id: create_release
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          file_pattern: '*.pdf'
          commit_message: 'Changed files'
