name: Build LaTeX document and Release PDF
# Version: 07142024
#
# Is executed at gooTeX script's prompt. 
# ############################
#      Pamela M. Marcum      #
#  first created: 07/14/2024 #
# ############################
# Controls when the action will run.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://mrturkmen.com/posts/build-release-latex/

on:
  workflow_dispatch:
    inputs: 
      file2compile:
         description: "Name of .tex file to compile, without the .tex part"
         required: true
         default: "main"
jobs:
  # followed: https://dev.to/dessygil/
  #   how-to-automatically-update-resume-on-your-personal-site-from-overleaf-1fld
  build_latex:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        
      - name: Tectonic Cache
        uses: actions/cache@v3
        # https://github.com/marketplace/actions/setup-tectonic
        # https://tectonic-typesetting.github.io/en-US/
        with:
          path: ~/.cache/Tectonic
          # can add ${{ hashFiles('**/*.tex') }} to invalidate cache on file changes
          key: ${{ runner.os }}-tectonic
          restore-keys: |
            ${{ runner.os }}-tectonic

      - name: Tectonic Setup
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Tectonic
        id: compilation
        run: |
           tectonic ${{ github.event.inputs.file2compile }}.tex &> tmpout.txt
        continue-on-error: true
        
      - name: Capture compilation output
        # remove lines in the output that are unrelated to the latex compilation itself
        # First, move lines that should have been the ending of the previous line, to the end of that previous line
        run: |
           sed ':a;N;$!ba;s/\n/\x0/g' tmpout.txt | \
              sed -r 's/\x0+/\x0/g' | \
              sed -r 's/ *\x0 */\x0/g' | \
              sed -r 's/\ *\: */\:/g' | \
              sed -r 's/\.\x0+([a-zA-Z]+)\:/\.\n\1\:/g' | \
              sed -r 's/\x0+/\n/g' > tmptmpout.txt
           mv -f tmptmpout.txt tmpout.txt
           grep "\.tex" tmpout.txt > tmptmpout.txt
           mv -f tmptmpout.txt tmpout.txt
           sort tmpout.txt | uniq > tmptmpout.txt
           mv -f tmptmpout.txt tmpout.txt
           cp ${{ github.event.inputs.file2compile }}.tex tmptmp.tex
           touch tout.txt
           while IFS= read -r line; do
              echo "$line" >> tout.txt
              # squash.io/extracting=numbers-from-strings-in-bash
              # https://stackoverflow.com/questions/17883661/how-to-extract-numbers-from-a-string
              # https://stackoverflow.com/questions/2624300/save-part-of-matching-pattern-to-variable
              linenum=$(echo "$line" | sed 's/^.*:\([0-9]*\):.*/\1/')
              sed -n "${linenum}p" tmptmp.tex >> tout.txt
              echo "-------------------------------------------------------------------------" >> tout.txt
           done<tmpout.txt
           rm -f tmptmp.tex
           mv -f tout.txt tmpout.txt
    
      - name: Turn failed compilation error to pdf
        if: steps.compilation.outcome != 'success'
        run: |         
          sudo apt-get install -y libreoffice
          cp tmpout.txt tmppdf.txt
          libreoffice --convert-to "pdf" tmppdf.txt
          rm -f tmppdf.txt
          mv -f tmppdf.pdf ${{ github.event.inputs.file2compile }}.pdf 
        
      - name: Rename output text file
        run: |
          mv -f tmpout.txt ${{ github.event.inputs.file2compile }}_out.txt
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with: 
          name: PDF
          path: "${{ github.event.inputs.file2compile }}.pdf"
          
      - name: Upload compilation output file
        uses: actions/upload-artifact@v4
        with: 
          name: compileOutput
          path: "${{ github.event.inputs.file2compile }}_out.txt"
          
      - name: Publish PDF to repo
        id: release_pdf
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          file_pattern: '${{ github.event.inputs.file2compile }}.pdf ${{ github.event.inputs.file2compile }}_out.txt'
          commit_message: 'Newly compiled PDF'
          
